import React, { createContext, useContext, useState } from 'react'

export const LANGUAGES = {
  en: { name: 'English', native: 'English', script: 'Latin' },
  hi: { name: 'Hindi', native: 'हिन्दी', script: 'Devanagari' },
  as: { name: 'Assamese', native: 'অসমীয়া', script: 'Assamese' },
  bn: { name: 'Bengali', native: 'বাংলা', script: 'Bengali' },
  mni: { name: 'Meitei', native: 'মৈতৈলোন্', script: 'Meitei' },
  lus: { name: 'Mizo', native: 'Mizo ṭawng', script: 'Latin' },
  kha: { name: 'Khasi', native: 'Khasi', script: 'Latin' },
  grt: { name: 'Garo', native: 'Garo', script: 'Latin' },
  trp: { name: 'Kokborok', native: 'Kokborok', script: 'Latin' },
  ne: { name: 'Nepali', native: 'नेपाली', script: 'Devanagari' },
} as const

export type LanguageCode = keyof typeof LANGUAGES

interface LanguageContextType {
  language: LanguageCode
  setLanguage: (lang: LanguageCode) => void
  lang: LanguageCode
  setLang: (lang: LanguageCode) => void
  languages: typeof LANGUAGES
  t: (key: string) => string
}

export const translations: Record<string, Record<string, string>> = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.liveMap': 'Live Map',
    'nav.alerts': 'Alerts',
    'nav.routes': 'Routes',
    'nav.accessibility': 'Accessibility',
    'nav.settings': 'Settings',
    'nav.launchPlatform': 'Launch Platform',
    'nav.overview': '← Overview',

    // Dashboard
    'dashboard.title': 'Command Dashboard',
    'dashboard.live': 'LIVE',
    'dashboard.zonesMonitored': 'zones monitored',
    'status.northeastIndia': 'Northeast India',
    'status.activeRegion': 'Northeast India',
    'criticalAlerts': 'CRITICAL ALERTS',
    'common.viewAll': 'View All',
    'kpi.activeAlerts': 'Active Alerts',
    'kpi.safeShelters': 'Safe Shelters',
    'kpi.evacueesAssisted': 'Evacuees Assisted',
    'kpi.highRiskZones': 'High-Risk Zones',
    'kpi.inLastHour': 'in last hour',
    'kpi.activeInGrid': 'active in grid',
    'kpi.liveTriageLogs': 'live triage logs',
    'kpi.activeHazards': 'active hazards',

    // Map & Disasters
    'map.tacticalTitle': 'Northeast India Tactical Map',
    'map.liveGisCorridor': 'LIVE GIS CORRIDOR',
    'map.sub': '8 States · OpenStreetMap Open GIS Engine · Live Fleet & Reroute Telemetry',
    'disasters.title': 'Active Disasters',
    'disasters.monitoring': 'MONITORING',
    'disasters.stats': '3 active · 5 monitored',

    // Landing Page
    'hero.tagline': 'SIH 2026 PS ID: SIH26002 · DISASTER LOGISTICS COMMAND',
    'hero.title1': 'Smarter Logistics',
    'hero.title2': 'for a',
    'hero.titleHighlight': 'Safer Tomorrow',
    'hero.subtitle': 'AI-powered dynamic rerouting, real-time landslide & flood alerts, and incline-audited accessible supply chains across the 8 states of Northeast India.',
    'hero.ctaLaunch': 'Launch Operations',
    'hero.ctaInspect': 'Inspect Network',
    'hero.badge1': '8 States Monitored',
    'hero.badge2': 'Real-time Alerts',
    'hero.badge3': 'Accessible Routes',
    'hero.badge4': 'Offline Resilient',
    'multilingual.title': 'Speak Your Language',
    'multilingual.subtitle': 'Engineered with localization architecture for the 10 major languages of Northeast India.',
    'multilingual.note': 'English fallback architecture guarantees seamless stability across all modules.',
    'accessibility.title': 'Accessibility for Everyone',
    'accessibility.subtitle': 'Emergency routes should move people forward — not leave anyone behind. Audited slope grades, wheelchair verification, and voice assistance.',
    'footer.tagline': 'Northeast Disaster Logistics Command',
    'footer.copyright': '© 2026 SmartLogix · A Smart India Hackathon Initiative. All rights reserved.',
  },

  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.liveMap': 'लाइव मैप',
    'nav.alerts': 'अलर्ट',
    'nav.routes': 'मार्ग',
    'nav.accessibility': 'सुगम्यता',
    'nav.settings': 'सेटिंग्स',
    'nav.launchPlatform': 'प्लेटफ़ॉर्म लॉन्च करें',
    'nav.overview': '← अवलोकन',

    'dashboard.title': 'कमांड डैशबोर्ड',
    'dashboard.live': 'लाइव',
    'dashboard.zonesMonitored': 'क्षेत्र निगरानी में',
    'status.northeastIndia': 'पूर्वोत्तर भारत',
    'status.activeRegion': 'पूर्वोत्तर भारत',
    'criticalAlerts': 'गंभीर अलर्ट',
    'common.viewAll': 'सभी देखें',
    'kpi.activeAlerts': 'सक्रिय अलर्ट',
    'kpi.safeShelters': 'सुरक्षित आश्रय',
    'kpi.evacueesAssisted': 'सहायता प्राप्त विस्थापित',
    'kpi.highRiskZones': 'उच्च जोखिम वाले क्षेत्र',
    'kpi.inLastHour': 'पिछले एक घंटे में',
    'kpi.activeInGrid': 'ग्रिड में सक्रिय',
    'kpi.liveTriageLogs': 'लाइव ट्राइएज लॉग',
    'kpi.activeHazards': 'सक्रिय खतरे',

    'map.tacticalTitle': 'पूर्वोत्तर भारत सामरिक मानचित्र',
    'map.liveGisCorridor': 'लाइव जीआईएस कॉरिडोर',
    'map.sub': '8 राज्य · ओपनस्ट्रीटमैप ओपन जीआईएस इंजन · लाइव फ्लीट और पुनःमार्ग टेलीमेट्री',
    'disasters.title': 'सक्रिय आपदाएँ',
    'disasters.monitoring': 'निगरानी',
    'disasters.stats': '3 सक्रिय · 5 निगरानी में',

    'hero.tagline': 'एस.आई.एच 2026 पी.एस: SIH26002 · आपदा रसद कमान',
    'hero.title1': 'स्मार्ट रसद',
    'hero.title2': 'एक',
    'hero.titleHighlight': 'सुरक्षित कल के लिए',
    'hero.subtitle': 'एआई-संचालित गतिशील पुनःमार्ग, वास्तविक समय भूस्खलन और बाढ़ चेतावनी, और पूर्वोत्तर भारत के 8 राज्यों में सुगम्य आपूर्ति श्रृंखला।',
    'hero.ctaLaunch': 'अभियान शुरू करें',
    'hero.ctaInspect': 'नेटवर्क की जाँच करें',
    'hero.badge1': '8 राज्य निगरानी में',
    'hero.badge2': 'वास्तविक समय अलर्ट',
    'hero.badge3': 'सुगम्य मार्ग',
    'hero.badge4': 'ऑफ़लाइन सक्षम',
    'multilingual.title': 'अपनी भाषा में बात करें',
    'multilingual.subtitle': 'पूर्वोत्तर भारत की 10 प्रमुख भाषाओं के लिए स्थानीयकरण वास्तुकला के साथ निर्मित।',
    'multilingual.note': 'अंग्रेजी फ़ॉलबैक वास्तुकला सभी मॉड्यूल में निर्बाध स्थिरता की गारंटी देती है।',
    'accessibility.title': 'सबके लिए सुगम्यता',
    'accessibility.subtitle': 'आपातकालीन मार्गों को सभी को आगे ले जाना चाहिए। ढलान ग्रेडिंग, व्हीलचेयर सत्यापन और ध्वनि सहायता।',
    'footer.tagline': 'पूर्वोत्तर आपदा रसद कमान',
    'footer.copyright': '© 2026 स्मार्टलॉजिक्स · स्मार्ट इंडिया हैकथॉन पहल। सर्वाधिकार सुरक्षित।',
  },

  as: {
    'nav.dashboard': 'ডেশ্ববৰ্ড',
    'nav.liveMap': 'লাইভ মেপ',
    'nav.alerts': 'সতৰ্কবাৰ্তা',
    'nav.routes': 'পথসমূহ',
    'nav.accessibility': 'সুগম্যতা',
    'nav.settings': 'ছেটিংছ',
    'nav.launchPlatform': 'প্লেটফৰ্ম আৰম্ভ',
    'nav.overview': '← অৱলোকন',

    'dashboard.title': 'কমাণ্ড ডেশ্ববৰ্ড',
    'dashboard.live': 'লাইভ',
    'dashboard.zonesMonitored': 'মণ্ডল নিৰীক্ষণ কৰা হৈছে',
    'status.northeastIndia': 'উত্তৰ-পূৱ ভাৰত',
    'status.activeRegion': 'উত্তৰ-পূৱ ভাৰত',
    'criticalAlerts': 'জৰুৰী সতৰ্কবাৰ্তা',
    'common.viewAll': 'সকলো চাওক',
    'kpi.activeAlerts': 'সক্ৰিয় সতৰ্কবাৰ্তা',
    'kpi.safeShelters': 'সুৰক্ষিত আশ্ৰয়স্থল',
    'kpi.evacueesAssisted': 'সহায়তাপ্ৰাপ্ত স্থানান্তৰিত লোক',
    'kpi.highRiskZones': 'উচ্চ আশংকাযুক্ত মণ্ডল',
    'kpi.inLastHour': 'যোৱা এক ঘণ্টাত',
    'kpi.activeInGrid': 'গ্ৰিডত সক্ৰিয়',
    'kpi.liveTriageLogs': 'লাইভ ট্ৰায়েজর তথ্য',
    'kpi.activeHazards': 'সক্ৰিয় বিপদ',

    'map.tacticalTitle': 'উত্তৰ-পূৱ ভাৰত ট্যাকটিকেল মানচিত্ৰ',
    'map.liveGisCorridor': 'লাইভ জিআইএছ কৰিডৰ',
    'map.sub': '৮ খন ৰাজ্য · অপেনষ্ট্ৰীটমেপ জিআইএছ ইঞ্জিন · লাইভ যান-বাহন আৰু বিকল্প পথ নিৰীক্ষণ',
    'disasters.title': 'সক্ৰিয় দুৰ্যোগ',
    'disasters.monitoring': 'নিৰীক্ষণ চলি আছে',
    'disasters.stats': '৩ সক্ৰিয় · ৫ নিৰীক্ষণাধীন',

    'hero.tagline': 'এছ.আই.এইচ ২০২৬: SIH26002 · দুৰ্যোগ লজিষ্টিকছ কমাণ্ড',
    'hero.title1': 'স্মাৰ্ট লজিষ্টিকছ',
    'hero.title2': 'এক',
    'hero.titleHighlight': 'সুৰক্ষিত কাইলৈৰ বাবে',
    'hero.subtitle': 'উত্তৰ-পূৱ ভাৰতৰ ৮ খন ৰাজ্যত এআই-চালিত গতিশীল বিকল্প পথ, ভূমিষ্খলন আৰু বানপানীৰ সতৰ্কবাৰ্তা আৰু বিশেষভাৱে সুগম্য যোগান শৃংখল।',
    'hero.ctaLaunch': 'অভিযান আৰম্ভ কৰক',
    'hero.ctaInspect': 'নেটৱৰ্ক পৰিদৰ্শন কৰক',
    'hero.badge1': '৮ খন ৰাজ্য নিৰীক্ষণ',
    'hero.badge2': 'ৰিয়েল-টাইম সতৰ্কতা',
    'hero.badge3': 'সুগম্য পথ',
    'hero.badge4': 'অফলাইন সক্ষম',
    'multilingual.title': 'আপোনাৰ ভাষাত কওক',
    'multilingual.subtitle': 'উত্তৰ-পূৱ ভাৰতৰ ১০ টা মুখ্য ভাষাৰ স্থানীয়কৰণ স্থাপত্যৰে নিৰ্মিত।',
    'multilingual.note': 'ইংৰাজী ফলবেক আৰ্কিটেকচাৰে সকলো মডিউলতে স্থিৰতা নিশ্চিত কৰে।',
    'accessibility.title': 'সকলোৰে বাবে সুগম্যতা',
    'accessibility.subtitle': 'জৰুৰীকালীন পথে কাকো এৰি নাযায়। প্ৰমাণিত ঢাল, হুইলচেয়াৰ পৰীক্ষা আৰু ধ্বনি নিৰ্দেশনা।',
    'footer.tagline': 'উত্তৰ-পূৱ দুৰ্যোগ লজিষ্টিকছ কমাণ্ড',
    'footer.copyright': '© ২০২৬ স্মাৰ্টলজিক্স · স্মাৰ্ট ইণ্ডিয়া হেকথন পদক্ষেপ।',
  },

  bn: {
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.liveMap': 'লাইভ ম্যাপ',
    'nav.alerts': 'সতর্কবার্তা',
    'nav.routes': 'রুটসমূহ',
    'nav.accessibility': 'অ্যাক্সেসিবিলিটি',
    'nav.settings': 'সেটিংস',
    'nav.launchPlatform': 'প্ল্যাটফর্ম চালু করুন',
    'nav.overview': '← সামগ্রিক দৃশ্য',

    'dashboard.title': 'কমান্ড ড্যাশবোর্ড',
    'dashboard.live': 'লাইভ',
    'dashboard.zonesMonitored': 'অঞ্চল নজরদারিতে',
    'status.northeastIndia': 'উত্তর-পূর্ব ভারত',
    'status.activeRegion': 'উত্তর-পূর্ব ভারত',
    'criticalAlerts': 'জরুরি সতর্কতা',
    'common.viewAll': 'সব দেখুন',
    'kpi.activeAlerts': 'সক্রিয় সতর্কতা',
    'kpi.safeShelters': 'নিরাপদ আশ্রয়কেন্দ্র',
    'kpi.evacueesAssisted': 'সহায়তাপ্রাপ্ত স্থানান্তরকারী',
    'kpi.highRiskZones': 'উচ্চ ঝুঁকিপূর্ণ এলাকা',
    'kpi.inLastHour': 'গত এক ঘণ্টায়',
    'kpi.activeInGrid': 'গ্রিডে সক্রিয়',
    'kpi.liveTriageLogs': 'লাইভ ট্রায়াজ লগ',
    'kpi.activeHazards': 'সক্রিয় বিপদ',

    'map.tacticalTitle': 'উত্তর-পূর্ব ভারত ট্যাকটিক্যাল ম্যাপ',
    'map.liveGisCorridor': 'লাইভ জিআইএস করিডোর',
    'map.sub': '৮টি রাজ্য · ওপেনস্ট্রিটম্যাপ জিআইএস ইঞ্জিন · লাইভ যানবাহন ও ডাইনামিক রুট',
    'disasters.title': 'সক্রিয় দুর্যোগ',
    'disasters.monitoring': 'নজরদারি',
    'disasters.stats': '৩টি সক্রিয় · ৫টি পর্যবেক্ষণাধীন',

    'hero.tagline': 'এসআইএইচ ২০২৬ পিএস: SIH26002 · দুর্যোগ লজিস্টিক কমান্ড',
    'hero.title1': 'স্মার্ট লজিস্টিক',
    'hero.title2': 'একটি',
    'hero.titleHighlight': 'নিরাপদ আগামী',
    'hero.subtitle': 'উত্তর-পূর্ব ভারতের ৮টি রাজ্যে এআই-চালিত গতিশীল পুনর্বিন্যাস, রিয়েল-টাইম ভূমিধস ও বন্যা সতর্কতা এবং বিশেষ সক্ষমতা-বান্ধব সরবরাহ শৃঙ্খল।',
    'hero.ctaLaunch': 'অভিযান শুরু করুন',
    'hero.ctaInspect': 'নেটওয়ার্ক পরিদর্শন',
    'hero.badge1': '৮টি রাজ্য নজরদারিতে',
    'hero.badge2': 'রিয়েল-টাইম সতর্কতা',
    'hero.badge3': 'সুগম রুট',
    'hero.badge4': 'অফলাইন কার্যকর',
    'multilingual.title': 'আপনার ভাষায় জানুন',
    'multilingual.subtitle': 'উত্তর-পূর্ব ভারতের ১০টি প্রধান ভাষার জন্য স্থানীয়করণ স্থাপত্য দ্বারা নির্মিত।',
    'multilingual.note': 'ইংরেজি ফলব্যাক আর্কিটেকচার সমস্ত মডিউলে নিরবচ্ছিন্ন স্থিতিশীলতা নিশ্চিত করে।',
    'accessibility.title': 'সকলের জন্য সুগম্যতা',
    'accessibility.subtitle': 'জরুরি রুটগুলি সবাইকে এগিয়ে নেবে — কাউকে পিছনে ফেলে নয়। যাচাইকৃত গ্রেডিয়েন্ট ও ভয়েস সহায়তা।',
    'footer.tagline': 'উত্তর-পূর্ব দুর্যোগ লজিস্টিক কমান্ড',
    'footer.copyright': '© ২০২৬ স্মার্টলজিক্স · স্মার্ট ইন্ডিয়া হ্যাকাথন উদ্যোগ।',
  },

  mni: {
    'nav.dashboard': 'দ্যাশবোর্দ',
    'nav.liveMap': 'লাইভ মেপ',
    'nav.alerts': 'চেকশিনৱা',
    'nav.routes': 'লম্বীশিং',
    'nav.accessibility': 'য়ৌবা ঙম্বা',
    'nav.settings': 'সেতিংশিং',
    'nav.launchPlatform': 'প্লাতফোর্ম হাংদোকউ',
    'nav.overview': '← য়েংশিনবা',

    'dashboard.title': 'কমেন্দ দ্যাশবোর্দ',
    'dashboard.live': 'লাইভ',
    'dashboard.zonesMonitored': 'জোন য়েংশিল্লিবা',
    'status.northeastIndia': 'অৱাং নোংপোক ভারত',
    'status.activeRegion': 'অৱাং নোংপোক ভারত',
    'criticalAlerts': 'য়াম্না মরুওইবা চেকশিনৱা',
    'common.viewAll': 'পুম্নমক য়েংউ',
    'kpi.activeAlerts': 'হৌজিক লৈরিবা চেকশিনৱা',
    'kpi.safeShelters': 'অচেতপা লৈফমশিং',
    'kpi.evacueesAssisted': 'মতেং ফংলবা মীওইশিং',
    'kpi.highRiskZones': 'অকুপ্পা জোনশিং',
    'kpi.inLastHour': 'হৌখিবা পুং অমদা',
    'kpi.activeInGrid': 'গ্রিদতা লৈবা',
    'kpi.liveTriageLogs': 'লাইভ ত্রিআজ লোগ',
    'kpi.activeHazards': 'হৌজিক লৈরিবা খুদোংথিবশিং',

    'map.tacticalTitle': 'অৱাং নোংপোক ভারতকী ট্যাকতিকেল মেপ',
    'map.liveGisCorridor': 'লাইভ জিআইএস লম্বী',
    'map.sub': 'রাজ্য ৮ · ওপেনস্ত্রীতম্যাপ · লাইভ গারী অমসুং লম্বী য়েংশিনবা',
    'disasters.title': 'হৌজিক থোক্লিবা খুদোংথিবশিং',
    'disasters.monitoring': 'য়েংশিনবা',
    'disasters.stats': '৩ হৌজিক · ৫ য়েংশিল্লি',

    'hero.tagline': 'SIH 2026: SIH26002 · খুদোংথীবা লজিস্তিক্স কমেন্দ',
    'hero.title1': 'স্মার্ত লজিস্তিক্স',
    'hero.title2': 'অমগীদমক',
    'hero.titleHighlight': 'অচেৎপা কদোমদা',
    'hero.subtitle': 'ভারতকী অৱাং-নোংপোক রাজ্য ৮দা এ.আই-না শেম্বা অনৌবা লম্বী, ঈচাউ অমসুং চিং থুংবগী পাউ, অমসুং মীওই পুম্নমক্না চৎপা য়াবা লম্বী।',
    'hero.ctaLaunch': 'অপরেসন হৌদোকউ',
    'hero.ctaInspect': 'নেতৱার্ক য়েংশিনবা',
    'hero.badge1': 'রাজ্য ৮ য়েংশিল্লি',
    'hero.badge2': 'হৌজিক্কী পাউ',
    'hero.badge3': 'চৎপা য়াবা লম্বী',
    'hero.badge4': 'ওফলাইন য়ারিবা',
    'multilingual.title': 'নহাক্কী লোনদা ঙাংউ',
    'multilingual.subtitle': 'অৱাং নোংপোক ভারতকী মরুওইবা লোন ১০গীদমক শেম্বা।',
    'multilingual.note': 'ইংলিশ ফোলবেক্কী খুথাংদা অচেৎপা ওইহল্লি।',
    'accessibility.title': 'মীওই পুম্নমক্কীদমক',
    'accessibility.subtitle': 'জরুরি লম্বীশিংনা কনগুম্বা অমত্তবু কান্নহন্দনা মী পুম্নমকপু মাংলোইশিনহনগনি।',
    'footer.tagline': 'অৱাং নোংপোক খুদোংথীবা লজিস্তিক্স কমেন্দ',
    'footer.copyright': '© ২০২৬ স্মার্তলজিক্স · স্মার্ত ইন্দিয়া হেকথন।',
  },

  lus: {
    'nav.dashboard': 'Dashboard',
    'nav.liveMap': 'Map Nung',
    'nav.alerts': 'Fimkhurna',
    'nav.routes': 'Kawngte',
    'nav.accessibility': 'Pawh Samna',
    'nav.settings': 'Hmanrua',
    'nav.launchPlatform': 'Platform Hawng Rawh',
    'nav.overview': '← Enkualna',

    'dashboard.title': 'Command Dashboard',
    'dashboard.live': 'NUNG',
    'dashboard.zonesMonitored': 'bial vil mekte',
    'status.northeastIndia': 'Hmar-Chhak India',
    'status.activeRegion': 'Hmar-Chhak India',
    'criticalAlerts': 'FIMKHURNA HRAWL',
    'common.viewAll': 'A Zavain En Rawh',
    'kpi.activeAlerts': 'Fimkhurna Awm Mek',
    'kpi.safeShelters': 'Himna Hmun',
    'kpi.evacueesAssisted': 'Chhanchhuah Tawkte',
    'kpi.highRiskZones': 'Hmun Hlauthawmawm',
    'kpi.inLastHour': 'darkar liamta ah',
    'kpi.activeInGrid': 'grid ah hman mek',
    'kpi.liveTriageLogs': 'enkawlna chhinchhiah',
    'kpi.activeHazards': 'hlauhawm awm mekte',

    'map.tacticalTitle': 'Hmar-Chhak India Tactical Map',
    'map.liveGisCorridor': 'LIVE GIS CORRIDOR',
    'map.sub': 'State 8 · OpenStreetMap GIS Engine · Motor tlan leh kawng him zawnna',
    'disasters.title': 'Chhiatrupna Awm Mek',
    'disasters.monitoring': 'VIL MEK',
    'disasters.stats': '3 nung · 5 vil mek',

    'hero.tagline': 'SIH 2026: SIH26002 · Chhiatrupna Enkawlna',
    'hero.title1': 'Logistics Fing Zawk',
    'hero.title2': 'tan',
    'hero.titleHighlight': 'Naktuk Him Zawk',
    'hero.subtitle': 'Hmar-Chhak state 8-ahte AI hmanga kawng thar zawn zung zungna, leimin leh tui lian hriattirna, leh harsatna nei te tana kawng him siamna.',
    'hero.ctaLaunch': 'Hna Tan Rawh',
    'hero.ctaInspect': 'Network Enchhin',
    'hero.badge1': 'State 8 Vil Mek',
    'hero.badge2': 'Hriattirna Rang',
    'hero.badge3': 'Kawng Him',
    'hero.badge4': 'Offline-ah Pawh A Tluang',
    'multilingual.title': 'I Ṭawngin Hmang Rawh',
    'multilingual.subtitle': 'Hmar-Chhak India ṭawng lian 10 tana siam a ni.',
    'multilingual.note': 'English fallback architecture hian harsatna awm loh nan a pui vek.',
    'accessibility.title': 'Mi Zawng Zawng Tan',
    'accessibility.subtitle': 'Kawng harsa zawh theih loh awm lo turin, wheelchair leh puihna mamawh te tan kawng buatsaih vek a ni.',
    'footer.tagline': 'Hmar-Chhak Chhiatrupna Enkawlna',
    'footer.copyright': '© 2026 SmartLogix · Smart India Hackathon Initiative.',
  },

  kha: {
    'nav.dashboard': 'Dashboard',
    'nav.liveMap': 'Map Ba Im',
    'nav.alerts': 'Ki Maham',
    'nav.routes': 'Ki Lynti',
    'nav.accessibility': 'Ka Jingïaid Suk',
    'nav.settings': 'Ki Jingpynbeit',
    'nav.launchPlatform': 'Plie ïa ka Platform',
    'nav.overview': '← Peit Lyngba',

    'dashboard.title': 'Command Dashboard',
    'dashboard.live': 'BA IM',
    'dashboard.zonesMonitored': 'ki jaka ba peit ngor',
    'status.northeastIndia': 'Shatei Lam Mihngi India',
    'status.activeRegion': 'Shatei Lam Mihngi India',
    'criticalAlerts': 'KI MAHAM BA SHYRKHIEI',
    'common.viewAll': 'Peit Baroh',
    'kpi.activeAlerts': 'Ki Maham Ba Treikam',
    'kpi.safeShelters': 'Ki Jaka Riewspah',
    'kpi.evacueesAssisted': 'Ki Ba La Ïarap',
    'kpi.highRiskZones': 'Ki Jaka Ba Maian Maian',
    'kpi.inLastHour': 'ha ka kynta ba la leit',
    'kpi.activeInGrid': 'ha ka grid',
    'kpi.liveTriageLogs': 'ka jingpeit bniah',
    'kpi.activeHazards': 'ki jingma ba treikam',

    'map.tacticalTitle': 'Map ka Shatei Lam Mihngi',
    'map.liveGisCorridor': 'LIVE GIS CORRIDOR',
    'map.sub': '8 Jylla · OpenStreetMap GIS · Ki kali bad lynti ba shngain',
    'disasters.title': 'Ki Jingma Ba Don',
    'disasters.monitoring': 'PEIT NGOR',
    'disasters.stats': '3 ba im · 5 ba peit ngor',

    'hero.tagline': 'SIH 2026: SIH26002 · Ka Jingïada Jingma',
    'hero.title1': 'Ka Jingkit Ba Khraw',
    'hero.title2': 'na ka bynta',
    'hero.titleHighlight': 'Ka Lashai Ba Shngain',
    'hero.subtitle': 'Ka AI ba pyniaid thymmai ïa ki lynti, ki maham khyndew hap bad jingshlei um ha ki 8 tylli ki jylla ka Shatei Lam Mihngi.',
    'hero.ctaLaunch': 'Sdang ïa ka Kam',
    'hero.ctaInspect': 'Peit ïa ka Network',
    'hero.badge1': '8 Tylli ki Jylla',
    'hero.badge2': 'Ki Maham Mynta',
    'hero.badge3': 'Ki Lynti Ba Suk',
    'hero.badge4': 'Treikam Lada Ym Don Internet',
    'multilingual.title': 'Kren ha ka Ktien Jong Phi',
    'multilingual.subtitle': 'La pynkhreh na ka bynta ki 10 tylli ki ktien ba kongsan ha ka Shatei Lam Mihngi.',
    'multilingual.note': 'Ka jingpyndonkam ïa ka English ka ïada ba kan ïaid beit man ka por.',
    'accessibility.title': 'Ka Jingïaid Suk ïa Baroh',
    'accessibility.subtitle': 'Ki lynti bakylluid kiba ym iehnoh shadien ïano ïano. Ki lynti wheelchair bad jingïarap ktien.',
    'footer.tagline': 'Ka Kynhun Ïada Jingma ka Shatei Lam Mihngi',
    'footer.copyright': '© 2026 SmartLogix · Smart India Hackathon Initiative.',
  },

  grt: {
    'nav.dashboard': 'Dashboard',
    'nav.liveMap': 'Map Tanggimin',
    'nav.alerts': 'Mikrakatani',
    'nav.routes': 'Ramani Rama',
    'nav.accessibility': 'Re•angna Man•ani',
    'nav.settings': 'Namo Rongatani',
    'nav.launchPlatform': 'Platform Ko Okiate',
    'nav.overview': '← Ni•rokani',

    'dashboard.title': 'Command Dashboard',
    'dashboard.live': 'TANGGIMIN',
    'dashboard.zonesMonitored': 'ni•rokgimin biaprana',
    'status.northeastIndia': 'Salgro Salgipeng India',
    'status.activeRegion': 'Salgro Salgipeng India',
    'criticalAlerts': 'MONGSONGGIKO MIKRAKATANI',
    'common.viewAll': 'Pilakkon Nibo',
    'kpi.activeAlerts': 'Mikrakatani Dongenggipa',
    'kpi.safeShelters': 'Katnapchakani Biap',
    'kpi.evacueesAssisted': 'Dakchakaniko Man•giparang',
    'kpi.highRiskZones': 'Kenani Gnanggipa Biaprana',
    'kpi.inLastHour': 'antang buringo',
    'kpi.activeInGrid': 'grido donggipa',
    'kpi.liveTriageLogs': 'sanani itihas',
    'kpi.activeHazards': 'kenani gnanggiparang',

    'map.tacticalTitle': 'Salgro Salgipeng Tactical Map',
    'map.liveGisCorridor': 'LIVE GIS CORRIDOR',
    'map.sub': 'State 8 · OpenStreetMap GIS · Gari tlangani aro rama namgipako sandiani',
    'disasters.title': 'A•sel Nangenggipa',
    'disasters.monitoring': 'NI•ENGGA',
    'disasters.stats': '3 tanggimin · 5 niongga',

    'hero.tagline': 'SIH 2026: SIH26002 · A•sel Nangani Ni•rokani',
    'hero.title1': 'Senggnanggipa Logistics',
    'hero.title2': 'na',
    'hero.titleHighlight': 'Kakketgipa Kinala',
    'hero.subtitle': 'Salgro Salgipengni state 8-o AI chi rama dingtangko sandiani, a•a beani aro chi banani mikrakatani, aro sakantinan rama namgniko on•ani.',
    'hero.ctaLaunch': 'Kamko A•bachenggo',
    'hero.ctaInspect': 'Networkko Ni•chenggo',
    'hero.badge1': 'State 8-ko Niongga',
    'hero.badge2': 'Daan Mikrakatani',
    'hero.badge3': 'Namgipa Ramarang',
    'hero.badge4': 'Net Griyoba Man•ani',
    'multilingual.title': 'Nang•ni Ku•sikchi Agangbo',
    'multilingual.subtitle': 'Salgro Salgipengni ku•sik dal•gipa 10-na tarigimin.',
    'multilingual.note': 'Englishchi dakchakani pilakkon chu•sokata.',
    'accessibility.title': 'Sakantinan Man•na Gita',
    'accessibility.subtitle': 'Rama dingtangrang darangkoba gualjawa. Wheelchair aro ku•rangchi dakchakani.',
    'footer.tagline': 'Salgro Salgipeng A•sel Nangani Ni•rokani',
    'footer.copyright': '© 2026 SmartLogix · Smart India Hackathon Initiative.',
  },

  trp: {
    'nav.dashboard': 'Dashboard',
    'nav.liveMap': 'Live Map',
    'nav.alerts': 'Kukrukma',
    'nav.routes': 'Lama Rok',
    'nav.accessibility': 'Kotor Lama',
    'nav.settings': 'Settings',
    'nav.launchPlatform': 'Platform Chengnai',
    'nav.overview': '← Naimung',

    'dashboard.title': 'Command Dashboard',
    'dashboard.live': 'LIVE',
    'dashboard.zonesMonitored': 'zila khwlwi tongo',
    'status.northeastIndia': 'Northeast India',
    'status.activeRegion': 'Northeast India',
    'criticalAlerts': 'KUKRUKMA KTOR',
    'common.viewAll': 'Tabuk Naimung',
    'kpi.activeAlerts': 'Kukrukma Tongo',
    'kpi.safeShelters': 'Khumunghai Nok',
    'kpi.evacueesAssisted': 'Twlangjak Borok',
    'kpi.highRiskZones': 'Botor Khijuk Zila',
    'kpi.inLastHour': 'khoroksa bisi',
    'kpi.activeInGrid': 'grido tongo',
    'kpi.liveTriageLogs': 'live logs',
    'kpi.activeHazards': 'dukha tongo',

    'map.tacticalTitle': 'Northeast India Tactical Map',
    'map.liveGisCorridor': 'LIVE GIS CORRIDOR',
    'map.sub': 'State 8 · OpenStreetMap GIS Engine · Gari tei kaham lama naimung',
    'disasters.title': 'Hathai Dukha',
    'disasters.monitoring': 'NAIMUNG',
    'disasters.stats': '3 tongo · 5 naimung',

    'hero.tagline': 'SIH 2026: SIH26002 · Hamya Phano Khasarok',
    'hero.title1': 'Kotor Logistics',
    'hero.title2': 'bagwi',
    'hero.titleHighlight': 'Kahambai Khalamung',
    'hero.subtitle': 'Northeast India ni state 8-o AI bai lama rwnai, ha kwplaimung tei twi luimung kukrukma tei joto borok manna lama.',
    'hero.ctaLaunch': 'Khamni Chengnai',
    'hero.ctaInspect': 'Network Naimung',
    'hero.badge1': 'State 8 Naimung',
    'hero.badge2': 'Tabukni Kukrukma',
    'hero.badge3': 'Kotor Lama',
    'hero.badge4': 'Net Kwrlwi Man',
    'multilingual.title': 'Nini Kokbai Salai',
    'multilingual.subtitle': 'Northeast India ni 10 kotor kok rok bagwi teirwjak.',
    'multilingual.note': 'English fallback architecture joto kothomani thik tonai.',
    'accessibility.title': 'Joto Borok Bagwi',
    'accessibility.subtitle': 'Kaham lama rok joto borokno twlangnai — saobano yakarnai le nungla. Wheelchair tei kok swlai.',
    'footer.tagline': 'Northeast Hamya Phano Khasarok Command',
    'footer.copyright': '© 2026 SmartLogix · Smart India Hackathon Initiative.',
  },

  ne: {
    'nav.dashboard': 'ड्यासबोर्ड',
    'nav.liveMap': 'प्रत्यक्ष नक्सा',
    'nav.alerts': 'सचेतनाहरू',
    'nav.routes': 'मार्गहरू',
    'nav.accessibility': 'पहुँचयोग्यता',
    'nav.settings': 'सेटिङहरू',
    'nav.launchPlatform': 'प्लेटफर्म सुरु गर्नुहोस्',
    'nav.overview': '← सिंहावलोकन',

    'dashboard.title': 'आदेश ड्यासबोर्ड',
    'dashboard.live': 'प्रत्यक्ष',
    'dashboard.zonesMonitored': 'निगरानी गरिएका क्षेत्रहरू',
    'status.northeastIndia': 'उत्तर-पूर्वी भारत',
    'status.activeRegion': 'उत्तर-पूर्वी भारत',
    'criticalAlerts': 'अति महत्त्वपूर्ण सचेतनाहरू',
    'common.viewAll': 'सबै हेर्नुहोस्',
    'kpi.activeAlerts': 'सक्रिय सचेतनाहरू',
    'kpi.safeShelters': 'सुरक्षित आश्रयस्थलहरू',
    'kpi.evacueesAssisted': 'सहयोग प्राप्त विस्थापितहरू',
    'kpi.highRiskZones': 'उच्च जोखिम क्षेत्रहरू',
    'kpi.inLastHour': 'पछिल्लो एक घण्टामा',
    'kpi.activeInGrid': 'ग्रिडमा सक्रिय',
    'kpi.liveTriageLogs': 'प्रत्यक्ष उपचार लगहरू',
    'kpi.activeHazards': 'सक्रिय जोखिमहरू',

    'map.tacticalTitle': 'उत्तर-पूर्वी भारत सामरिक नक्सा',
    'map.liveGisCorridor': 'प्रत्यक्ष जीआईएस कोरिडोर',
    'map.sub': '८ राज्यहरू · ओपनस्ट्रिटम्याप जीआईएस इन्जिन · प्रत्यक्ष फ्लीट र पुनःमार्ग टेलिमेट्री',
    'disasters.title': 'सक्रिय विपद्हरू',
    'disasters.monitoring': 'निगरानी',
    'disasters.stats': '३ सक्रिय · ५ निगरानीमा',

    'hero.tagline': 'SIH 2026: SIH26002 · विपद् रसद कमान्ड',
    'hero.title1': 'स्मार्ट रसद',
    'hero.title2': 'एक',
    'hero.titleHighlight': 'सुरक्षित भोलिको लागि',
    'hero.subtitle': 'पूर्वोत्तर भारतका ८ राज्यहरूमा एআই-संचालित गतिशील पुनःमार्ग, पहिरो र बाढी सचेतना, र अपाङ्गता-मैत्री आपूर्ति श्रृंखला।',
    'hero.ctaLaunch': 'अभियान सुरु गर्नुहोस्',
    'hero.ctaInspect': 'नेटवर्क निरीक्षण गर्नुहोस्',
    'hero.badge1': '८ राज्यहरू निगरानीमा',
    'hero.badge2': 'प्रत्यक्ष सचेतना',
    'hero.badge3': 'पहुँचयोग्य मार्ग',
    'hero.badge4': 'अफलाइन सक्षम',
    'multilingual.title': 'आफ्नो भाषामा बोल्नुहोस्',
    'multilingual.subtitle': 'पूर्वोत्तर भारतका १० प्रमुख भाषाहरूको लागि स्थानीयकरण संरचनासहित निर्मित।',
    'multilingual.note': 'अंग्रेजी फलब्याक संरचनाले सबै मोड्युलहरूमा सहज स्थिरता सुनिश्चित गर्दछ।',
    'accessibility.title': 'सबैका लागि पहुँचयोग्यता',
    'accessibility.subtitle': 'आपत्कालीन मार्गहरूले सबैलाई अगाडि लैजानुपर्छ। प्रमाणित ढलान, ह्वीलचेयर परीक्षण र अडियो सहयोग।',
    'footer.tagline': 'पूर्वोत्तर विपद् रसद कमान्ड',
    'footer.copyright': '© २०२६ स्मार्टलजिक्स · स्मार्ट इन्डिया ह्याकाथन पहल।',
  },
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  lang: 'en',
  setLang: () => {},
  languages: LANGUAGES,
  t: (key: string) => key,
})

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('smartlogix_lang') as LanguageCode | null
    if (saved && saved in LANGUAGES) {
      return saved
    }
    return 'en'
  })

  const setLang = (newLang: LanguageCode) => {
    setLangState(newLang)
    localStorage.setItem('smartlogix_lang', newLang)
  }

  const t = (key: string): string => {
    if (translations[lang]?.[key]) return translations[lang][key]
    if (translations['en']?.[key]) return translations['en'][key]
    if (key.startsWith('nav.')) {
      const stripped = key.slice(4)
      if (translations[lang]?.[stripped]) return translations[lang][stripped]
      if (translations['en']?.[stripped]) return translations['en'][stripped]
    }
    return key
  }

  return (
    <LanguageContext.Provider value={{ language: lang, setLanguage: setLang, lang, setLang, languages: LANGUAGES, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
